### ISSUE TITLE
.

### ISSUE THREAD

**Issue by seekingdeep** [mariabg/CrowdfundingCampaignAnalyzer#2]
.

**Comment by mariabg** [comment]
yes, I am! What type of freelance are you looking for?

**Comment by seekingdeep** [comment]
basically analyzing data somewhat similar to this.
what is your upwork.com ?

**Comment by mariabg** [comment]
drop me a mail at my gmail account mariabenaventeg with the proposal and i'll send you my CV

**Comment by seekingdeep** [comment]
i preffer using upwork.com

**Comment by mariabg** [comment]
https://www.upwork.com/freelancers/~0186b4445f911d630c

**Comment by seekingdeep** [comment]
1 moment

**Comment by seekingdeep** [comment]
i can't invite you, why is that?
![upw](https://user-images.githubusercontent.com/71519088/105199663-0f788500-5b50-11eb-8286-3df9c2f24f2b.png)

**Comment by mariabg** [comment]
i just created the profile and I saw there is a msg: Your profile is under review We will email you within 24 hours to let you know if your profile was approved. You will be able to submit proposals if it is approved.

Were can I let you know that my profile is ready?

**Comment by seekingdeep** [comment]
let me know here,
it's basic, i want to analyze what makes a successful campaign or not.
but i want to ask more questions, such as if i choose to set the price as say 100, what should i choose for other factors, etc...
focus on a single category perhaps, etc....
basically, i want more customizability and flexibility

**Comment by mariabg** [comment]
@seekingdeep I was denied the invitation as they are trying to "maintain a balance between the availability of jobs and talent on our platform". Do you want to try through other platform?

**Comment by seekingdeep** [comment]
hmmmm.... you should have listed your skills "python, ....."
anyways, a lower tier website would be fiverr
send me a link to your account there

**Comment by mariabg** [comment]
https://www.fiverr.com/marabenaventegm?up_rollout=true

**Comment by seekingdeep** [comment]
1 moment

**Comment by seekingdeep** [comment]
create a gig in fiverr so i can contact

**Comment by seekingdeep** [comment]
i am still waiting

**Comment by mariabg** [comment]
good to know you keep waiting, i'm working on other stuff atm
